# Generated by Django 5.1.5 on 2025-03-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameriddle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='gameriddle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('game',), name='unique_active_riddle_per_game'),
        ),
    ]
